services:
  testcot:
    image: ghcr.io/spezifisch/docker-test-dovecot:latest
    volumes:
      - testcot-home:/home

  # fetch from a -> deliver to rxa
  mettmail_a:
    depends_on:
      - testcot
    build:
      context: mettmail
    image: mettmail
    volumes:
      - ./mettmail-a.yaml:/config/mettmail.yaml:ro
    command: [ "--trace", "--config", "/config/mettmail.yaml" ]
    restart: always

  # fetch from rxb -> deliver to rxc
  mettmail_rxb:
    depends_on:
      - testcot
    image: mettmail
    volumes:
      - ./mettmail-rxb.yaml:/config/mettmail.yaml:ro
    command: [ "--trace", "--config", "/config/mettmail.yaml" ]
    restart: always

  # test runner
  test:
    depends_on:
      - testcot
      - mettmail_a
      - mettmail_rxb
    image: bats/bats:1.5.0
    volumes:
      # bats test scripts
      - ./tests/bats:/tests:ro
      # test users home dirs
      - testcot-home:/home
    command: "/tests"

volumes:
  testcot-home: null
