name: docker-compose test
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                  path: mettmail
                  repository: spezifisch/mettmail

            - name: Start test dovecot and mettmails
              run: docker-compose -f ./docker-compose.test.yaml up -d testcot mettmail_a mettmail_rxb

            - name: Test
              run: docker-compose -f ./docker-compose.test.yaml up --build --exit-code-from test test
