name: docker-compose test
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/checkout@v2
              with:
                  path: "spezifisch/mettmail"

            - name: Test
              run: docker-compose -f ./docker-compose.test.yaml up --build --exit-code-from test
